/*
Name: Muhammad Hamza Khan
Student ID: 2502941
Assignment: 1
Question: 1
*/
#include <iostream>
#include <iomanip>
using namespace std;
int main()
{
    char window;
    cout << "Enter the symbol of windows: ";
    cin >> window;
    char stairs;
    cout << "Enter the symbol of stairs: ";
    cin >> stairs;
    cout << setw(60)<<"______________________________"<<endl
    <<setw(31)<<"|"<<setw(29)<<"|"<<endl
    <<setw(31)<<"|"<< setw(7)<<window<<setw(6)<<window<<setw(6)<<window<<setw(10)<<"|"<<endl
    <<setw(31)<<"|"<< setw(7)<<window<<setw(6)<<window<<setw(6)<<window<<setw(10)<<"|"<<endl
    <<setw(60)<<"|____________________________|"<<endl
    <<setw(30)<<"______________________________"<<setw(61)<<"_____________________________"<<endl
    <<setw(1)<<"|"<<setw(29)<<"|"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"|"<<setw(4)<<"|"<<setw(25)<<"|"<<endl
    <<setw(1)<<"|"<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<setw(3)<<"/"<<setw(4)<<"/"<<setw(4)<<"/"<<setw(5)<<window<<setw(1)<<window<<setw(1)<<window<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(4)<<"/"<<endl
    <<setw(1)<<"|"<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<setw(3)<<"/"<<setw(4)<<"/"<<setw(4)<<"/"<<setw(5)<<window<<setw(1)<<window<<setw(1)<<window<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(4)<<"/"<<endl
    <<setw(1)<<"|"<<setw(29)<<"____________________________|"<<setw(4)<<"|__|"<<setw(2)<<"|__|"<<setw(3)<<"|__|"<<setw(4)<<"|__|"<<setw(4)<<"|__|"<<setw(4)<<"|__|"<<setw(4)<<"|__|"<<setw(2)<<"|"<<setw(2)<<"|"<<setw(27)<<"|___________________________|"<<endl
    <<setw(29)<<"______________"<<setw(25)<<"_______________________"<<setw(15)<<"____________"<<endl
    <<setw(16)<<"|"<<setw(13)<<"|"<<setw(3)<<"|"<<setw(22)<<"|"<<setw(4)<<"|"<<setw(11)<<"|"<<endl
    <<setw(16)<<"|"<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(5)<<"/"<<setw(3)<<"/"<<setw(16)<<"Faculty of"<<setw(6)<<"/"<<setw(4)<<"/"<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(5)<<"/"<<endl
    <<setw(16)<<"|"<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(5)<<"/"<<setw(3)<<"/"<<setw(17)<<"Computing $ AI"<<setw(5)<<"/"<<setw(4)<<"/"<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(5)<<"/"<<endl
    <<setw(30)<<"|_____________|"<<setw(24)<<"|_____________________|"<<setw(4)<<"|"<<setw(11)<<"_________|"<<endl
    <<setw(53)<<"_____________________"<<endl
    <<setw(32)<<"/"<<setw(23)<<"\\"<<endl
    <<setw(31)<<"/"<<setw(25)<<"\\"<<endl
    <<setw(30)<<"/"<<setw(27)<<"\\"<<endl
    <<setw(29)<<"/"<<setw(28)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<"\\"<<endl
    <<setw(28)<<"/"<<setw(29)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<"\\"<<endl
    <<setw(27)<<"/"<<setw(30)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<"\\"<<endl
    <<setw(26)<<"/"<<setw(31)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<"\\"<<endl
    <<setw(25)<<"/"<<setw(32)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<"\\"<<endl
    <<setw(24)<<"/"<<setw(33)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<"\\"<<endl
    <<setw(23)<<"/"<<setw(34)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<"\\"<<endl
    <<setw(22)<<"/"<<setw(35)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<stairs<<setw(1)<<"\\"<<endl
    <<setw(21)<<"/"<<setw(36)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<"\\"<<endl
    <<setw(20)<<"/"<<setw(37)<<"______________________________________________"<<setw(1)<<"\\";
    return 0;
}