#include <iostream>
#include <iomanip>
using namespace std;
int main()
{
    char window;
    cout << "Enter the symbol of windows: ";
    cin >> window;
    char stairs;
    cout << "Enter the symbol of stairs: ";
    cin >> stairs;
    cout << setw(69)<<"_______________________________________"<<endl
    <<setw(31)<<"|"<<setw(38)<<"|"<<endl
    <<setw(31)<<"|"<< setw(4)<<window<<window<<window<<window<<setw(6)<<window<<window<<window<<window<<setw(6)<<window<<window<<window<<setw(6)<<window<<window<<window<<setw(6)<<"|"<<endl
    <<setw(31)<<"|"<< setw(4)<<window<<window<<window<<window<<setw(6)<<window<<window<<window<<window<<setw(6)<<window<<window<<window<<setw(10)<<setw(6)<<window<<window<<window<<setw(6)<<"|"<<endl
    <<setw(31)<<"|"<<"-------------------------------------"<<"|"<<endl
    <<setw(31)<<"|"<< setw(4)<<window<<window<<window<<window<<setw(6)<<window<<window<<window<<window<<setw(6)<<window<<window<<window<<setw(10)<<setw(6)<<window<<window<<window<<setw(6)<<"|"<<endl
    <<setw(31)<<"|"<< setw(4)<<window<<window<<window<<window<<setw(6)<<window<<window<<window<<window<<setw(6)<<window<<window<<window<<setw(10)<<setw(6)<<window<<window<<window<<setw(6)<<"|"<<endl
    <<setw(69)<<"|_____________________________________|"<<endl
    <<setw(30)<<"______________________________"<<setw(68)<<"______________________________"<<endl
    <<setw(1)<<"|"<<setw(29)<<"|"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(4)<<"__"<<setw(2)<<"|"<<setw(2)<<setw(30)<<"|"<<endl
    <<setw(1)<<"|"<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<setw(3)<<"/"<<setw(4)<<"/"<<setw(4)<<"/"<<setw(5)<<window<<setw(1)<<window<<setw(1)<<window<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(11)<<"/"<<endl
    <<setw(1)<<"|"<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(6)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<"/"<<setw(2)<<setw(3)<<"/"<<setw(4)<<"/"<<setw(4)<<"/"<<setw(5)<<window<<setw(1)<<window<<setw(1)<<window<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(11)<<"/"<<endl
    <<setw(1)<<"|"<<setw(29)<<"____________________________|"<<setw(4)<<"|__|"<<setw(2)<<"|__|"<<setw(3)<<"|__|"<<setw(4)<<"|__|"<<setw(4)<<"|__|"<<setw(4)<<"|__|"<<setw(4)<<"|__|"<<setw(4)<<"|__|"<<setw(4)<<"|__|"<<setw(32)<<"|______________________________|"<<endl
    <<setw(29)<<"______________"<<setw(37)<<"__________________________________"<<setw(15)<<"____________"<<endl
    <<setw(16)<<"|"<<setw(13)<<"|"<<setw(3)<<"|"<<setw(34)<<"|"<<setw(4)<<"|"<<setw(11)<<"|"<<endl
    <<setw(16)<<"|"<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(5)<<"/"<<setw(3)<<"/"<<setw(22)<<"Faculty of"<<setw(12)<<"/"<<setw(4)<<"/"<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(5)<<"/"<<endl
    <<setw(16)<<"|"<<setw(6)<<window<<setw(1)<<window<<setw(1)<<window<<setw(5)<<"/"<<setw(3)<<"/"<<setw(24)<<"Computing & AI"<<setw(10)<<"/"<<setw(4)<<"/"<<setw(4)<<window<<setw(1)<<window<<setw(1)<<window<<setw(5)<<"/"<<endl
    <<setw(30)<<"|_____________|"<<setw(36)<<"|_________________________________|"<<setw(4)<<"|"<<setw(11)<<"_________|"<<endl
    <<setw(60)<<"__________________________"<<endl
    <<setw(34)<<"/"<<setw(27)<<"\\"<<endl
    <<setw(33)<<"/"<<setw(29)<<"\\"<<endl
    <<setw(32)<<"/"<<setw(31)<<"\\"<<endl
    <<setw(31)<<"/"<<setw(33)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<"\\"<<endl
    <<setw(30)<<"/"<<setw(35)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<"\\"<<endl
    <<setw(29)<<"/"<<setw(37)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<"\\"<<endl
    <<setw(28)<<"/"<<setw(39)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<"\\"<<endl
    <<setw(27)<<"/"<<setw(41)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<"\\"<<endl
    <<setw(26)<<"/"<<setw(43)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<"\\"<<endl
    <<setw(25)<<"/"<<setw(45)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<"\\"<<endl
    <<setw(24)<<"/"<<setw(47)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<stairs<<setw(1)<<"\\"<<endl
    <<setw(23)<<"/"<<setw(49)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<stairs<<setw(1)<<stairs<<setw(1)<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<stairs<<setw(1)<<"\\"<<endl
    <<setw(22)<<"/"<<setw(50)<<"________________________________________________"<<setw(1)<<"\\";
    return 0;
}